## Part 1: Preprocessing

In [34]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [35]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [36]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]

# Preview the new DataFrame
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [37]:
# Create a list of at least 10 column names to use as X data
feature_columns = [
    "Age",
    "BusinessTravel",
    "DistanceFromHome",
    "Education",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobLevel",
    "MaritalStatus",
    "YearsSinceLastPromotion",
    "OverTime"
]

# Create X_df using your selected columns
X_df = attrition_df[feature_columns]

# Show the data types for X_df
X_df.dtypes


Age                         int64
BusinessTravel             object
DistanceFromHome            int64
Education                   int64
EnvironmentSatisfaction     int64
JobInvolvement              int64
JobLevel                    int64
MaritalStatus              object
YearsSinceLastPromotion     int64
OverTime                   object
dtype: object

In [38]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)

# Confirm the split worked
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1102, 10)
(368, 10)
(1102, 2)
(368, 2)


In [39]:
# Convert X_train and X_test to numeric using one-hot encoding
X_train_encoded = pd.get_dummies(X_train)
X_test_encoded = pd.get_dummies(X_test)

# Ensure the same columns exist in both sets
X_train_encoded, X_test_encoded = X_train_encoded.align(X_test_encoded, join='left', axis=1, fill_value=0)

# Preview encoded X_train
X_train_encoded.head()


Age  DistanceFromHome  Education  EnvironmentSatisfaction  \
464    37                 1          3                        2   
512    27                 3          4                        1   
480    30                12          4                        2   
680    36                 7          4                        2   
1023   56                 1          2                        1   

      JobInvolvement  JobLevel  YearsSinceLastPromotion  \
464                3         3                        1   
512                2         1                        1   
480                2         1                        0   
680                3         1                        0   
1023               3         1                        1   

      BusinessTravel_Non-Travel  BusinessTravel_Travel_Frequently  \
464                       False                             False   
512                       False                             False   
480                       False                              True   
680                       False                             False   
1023                      False                             False   

      BusinessTravel_Travel_Rarely  MaritalStatus_Divorced  \
464                           True                   False   
512                           True                   False   
480                          False                   False   
680                           True                   False   
1023                          True                   False   

      MaritalStatus_Married  MaritalStatus_Single  OverTime_No  OverTime_Yes  
464                   False                  True         True         False  
512                   False                  True         True         False  
480                    True                 False         True         False  
680                   False                  True         True         False  
1023                   True                 False         True         False

In [40]:
# Count the values in the 'OverTime' column of the training data
X_train["OverTime"].value_counts().to_frame(name="count")


count
OverTime       
No          798
Yes         304

In [41]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train_encoded)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

# Convert the scaled data back into DataFrames (so we retain the column names)
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train_encoded.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test_encoded.columns)

# Preview the scaled training data
X_train_scaled.head()


Age  DistanceFromHome  Education  EnvironmentSatisfaction  \
0 -0.000597         -1.009337   0.080843                -0.660419   
1 -1.097736         -0.761501   1.070722                -1.578176   
2 -0.768595          0.353763   1.070722                -0.660419   
3 -0.110311         -0.265828   1.070722                -0.660419   
4  2.083967         -1.009337  -0.909036                -1.578176   

   JobInvolvement  JobLevel  YearsSinceLastPromotion  \
0        0.373771  0.845308                -0.350760   
1       -1.013082 -0.963487                -0.350760   
2       -1.013082 -0.963487                -0.663492   
3        0.373771 -0.963487                -0.663492   
4        0.373771 -0.963487                -0.350760   

   BusinessTravel_Non-Travel  BusinessTravel_Travel_Frequently  \
0                  -0.347934                         -0.480921   
1                  -0.347934                         -0.480921   
2                  -0.347934                          2.079344   
3                  -0.347934                         -0.480921   
4                  -0.347934                         -0.480921   

   BusinessTravel_Travel_Rarely  MaritalStatus_Divorced  \
0                      0.648154               -0.531871   
1                      0.648154               -0.531871   
2                     -1.542844               -0.531871   
3                      0.648154               -0.531871   
4                      0.648154               -0.531871   

   MaritalStatus_Married  MaritalStatus_Single  OverTime_No  OverTime_Yes  
0              -0.914695              1.444588     0.617213     -0.617213  
1              -0.914695              1.444588     0.617213     -0.617213  
2               1.093261             -0.692239     0.617213     -0.617213  
3              -0.914695              1.444588     0.617213     -0.617213  
4               1.093261             -0.692239     0.617213     -0.617213

In [42]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data (make sure the column is passed as a DataFrame or 2D array)
encoder.fit(y_train[['Department']])

# Apply the encoder to the training and testing data
y_train_department_encoded = encoder.transform(y_train[['Department']])
y_test_department_encoded = encoder.transform(y_test[['Department']])

# Preview the encoded output for the training data
print(y_train_department_encoded)



[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [43]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder
encoder_attrition = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data (ensure 'Attrition' is passed as a DataFrame or 2D array)
encoder_attrition.fit(y_train[['Attrition']])

# Apply the encoder to the training and testing data
y_train_attrition_encoded = encoder_attrition.transform(y_train[['Attrition']])
y_test_attrition_encoded = encoder_attrition.transform(y_test[['Attrition']])

# Preview the encoded output for the training data
print(y_train_attrition_encoded)



[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Part 2: Create, Compile, and Train the Model

In [46]:
# Find the number of columns in the X training data
num_columns = X_train_scaled.shape[1]
print(f'Number of columns in X_train: {num_columns}')

# Create the input layer
input_layer = Input(shape=(num_columns,))

# Create at least two shared layers
shared_layer1 = Dense(64, activation='relu')(input_layer)
shared_layer2 = Dense(32, activation='relu')(shared_layer1)


Number of columns in X_train: 15


In [47]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer for the Department branch
dept_hidden = Dense(16, activation="relu")(shared_layer2)

# Create the output layer for the Department branch
dept_output = Dense(3, activation="softmax", name="department_output")(dept_hidden)



In [48]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer for the Attrition branch
attrition_hidden = Dense(16, activation="relu")(shared_layer2)

# Create the output layer for the Attrition branch
attrition_output = Dense(1, activation="sigmoid", name="attrition_output")(attrition_hidden)


In [50]:
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# Create the model
model = Model(inputs=input_layer, outputs=[attrition_output, dept_output])

# Compile the model
model.compile(
    loss={
        "attrition_output": "binary_crossentropy",
        "dept_output": "categorical_crossentropy"
    },
    optimizer=Adam(),
    metrics={
        "attrition_output": "accuracy",
        "dept_output": "accuracy"
    }
)

# Summarize the model
model.summary()


Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2       │ (None, 15)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 64)        │      1,024 │ input_layer_2[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 32)        │      2,080 │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 16)        │        528 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 16)        │        528 │ dense_5[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 1)         │         17 │ dense_7[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         51 │ dense_6[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 4,228 (16.52 KB)

 Trainable params: 4,228 (16.52 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
attrition_df.columns


Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [60]:
# 1. First, separate your features and targets from the full dataset
X = attrition_df.drop(['Attrition', 'Department'], axis=1)
y_attrition = attrition_df['Attrition']
y_department = attrition_df['Department']

# 2. Split into training and validation sets
from sklearn.model_selection import train_test_split

X_train, X_val, y_train_attrition, y_val_attrition = train_test_split(X, y_attrition, test_size=0.2, random_state=42)
_, _, y_train_department, y_val_department = train_test_split(X, y_department, test_size=0.2, random_state=42)


In [61]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Encode Attrition (binary classification)
le_attrition = LabelEncoder()
y_train_attrition_enc = le_attrition.fit_transform(y_train_attrition)
y_val_attrition_enc = le_attrition.transform(y_val_attrition)

# Encode Department (multi-class classification)
le_dept = LabelEncoder()
y_train_department_enc = le_dept.fit_transform(y_train_department)
y_val_department_enc = le_dept.transform(y_val_department)

# One-hot encode department for softmax output
y_train_department_ohe = to_categorical(y_train_department_enc)
y_val_department_ohe = to_categorical(y_val_department_enc)


In [63]:
# Combine the full dataset before splitting to keep feature columns aligned
X_encoded = pd.get_dummies(X)

# Re-split the encoded features using the same random state
X_train, X_val = train_test_split(X_encoded, test_size=0.2, random_state=42)


In [65]:
# Ensure all data in X is numeric and of float32 type
X_train = X_train.astype('float32')
X_val = X_val.astype('float32')


In [66]:
print(X_train.dtypes)


Age                                  float32
DistanceFromHome                     float32
Education                            float32
EnvironmentSatisfaction              float32
HourlyRate                           float32
JobInvolvement                       float32
JobLevel                             float32
JobSatisfaction                      float32
NumCompaniesWorked                   float32
PercentSalaryHike                    float32
PerformanceRating                    float32
RelationshipSatisfaction             float32
StockOptionLevel                     float32
TotalWorkingYears                    float32
TrainingTimesLastYear                float32
WorkLifeBalance                      float32
YearsAtCompany                       float32
YearsInCurrentRole                   float32
YearsSinceLastPromotion              float32
YearsWithCurrManager                 float32
BusinessTravel_Non-Travel            float32
BusinessTravel_Travel_Frequently     float32
BusinessTr

In [68]:
print(type(y_train_attrition_enc), y_train_attrition_enc.dtype)
print(type(y_train_department_ohe), y_train_department_ohe.dtype)


<class 'numpy.ndarray'> int64
<class 'numpy.ndarray'> float64


In [69]:
import numpy as np

# Ensure correct dtypes
y_train_attrition_enc = np.array(y_train_attrition_enc).astype('int32')
y_val_attrition_enc = np.array(y_val_attrition_enc).astype('int32')

y_train_department_ohe = np.array(y_train_department_ohe).astype('float32')
y_val_department_ohe = np.array(y_val_department_ohe).astype('float32')


In [71]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam

# Input layer
input_layer = Input(shape=(X_train.shape[1],))

# Shared hidden layers
x = Dense(64, activation='relu')(input_layer)
x = Dense(32, activation='relu')(x)

# Output 1: Binary classification (Attrition)
attrition_output = Dense(1, activation='sigmoid', name='attrition_output')(x)

# Output 2: Multi-class classification (Department)
department_output = Dense(y_train_department_ohe.shape[1], activation='softmax', name='department_output')(x)

# Create the model
model = Model(inputs=input_layer, outputs=[attrition_output, department_output])

# Compile it with two loss functions and appropriate metrics
model.compile(
    optimizer=Adam(),
    loss={
        'attrition_output': 'binary_crossentropy',
        'department_output': 'categorical_crossentropy'
    },
    metrics={
        'attrition_output': 'accuracy',
        'department_output': 'accuracy'
    }
)


In [72]:
# Train the model
history = model.fit(
    X_train,
    {
        'attrition_output': y_train_attrition_enc,
        'department_output': y_train_department_ohe
    },
    validation_data=(
        X_val,
        {
            'attrition_output': y_val_attrition_enc,
            'department_output': y_val_department_ohe
        }
    ),
    epochs=100,
    batch_size=32
)

Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - attrition_output_accuracy: 0.4300 - attrition_output_loss: 3.2205 - department_output_accuracy: 0.3655 - department_output_loss: 4.2580 - loss: 7.4795 - val_attrition_output_accuracy: 0.8639 - val_attrition_output_loss: 0.4035 - val_department_output_accuracy: 0.5170 - val_department_output_loss: 0.9121 - val_loss: 1.3637
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - attrition_output_accuracy: 0.8345 - attrition_output_loss: 0.4571 - department_output_accuracy: 0.5928 - department_output_loss: 0.9665 - loss: 1.4236 - val_attrition_output_accuracy: 0.8571 - val_attrition_output_loss: 0.3615 - val_department_output_accuracy: 0.6735 - val_department_output_loss: 0.7568 - val_loss: 1.1398
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8216 - attrition_output_loss: 0.4492 - department_output_accuracy: 0.6622 - department_output_loss: 0.7572 - loss: 1.2066 - val_attrition_output_accuracy: 0.8639 -

In [73]:
# Evaluate the model with test data
test_loss, attrition_accuracy, department_accuracy = model.evaluate(
    X_test,
    {
        'attrition_output': y_test_attrition_enc,
        'department_output': y_test_department_ohe
    },
    batch_size=32
)

# Print the results
print(f"Test Loss: {test_loss}")
print(f"Attrition Accuracy: {attrition_accuracy}")
print(f"Department Accuracy: {department_accuracy}")



NameError: name 'y_test_attrition_enc' is not defined

In [ ]:
# Print the accuracy for both department and attrition


Attrition predictions accuracy: 0.7880434989929199
Department predictions accuracy: 0.5


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.